const fr = {
	headerText: "Pylos - Le Jeu",
	footerText: "SlipSoft - 2018",
	refresh: "Rafraîchir",
	refreshing: "Rafraichissement en cours",
	disconnect: "Se déconnecter",
	login: "Se connecter",
	register: "S'enregistrer",
	loginText: "Deja un compte ? cliquez ici",
	registerText: "Pas encore de compte ? Cliquez ici",
	loginFieldText: "Identifiant de connexion",
	passwordFieldText: "Mot de passe",
	passwordConfirmationFieldText: "Retapez votre mot de passe",
	usernameFieldText: "Nom d'utilisateur",
	unknownError: "Une erreur inconnue s'est produite, veuillez réessayer plus tard",
	internalServerError: "IErreur interne, veuillez réessayer plus tard",
	404: "Erreur 404: ressource non disponible",
	missingAuth: "Authentification manquante",
	invalidAuth: "Authentification Invalide",
	unavailableData: "Données non disponibles",
	invalidLogin: "Login Invalide",
	loginInUse: "Login déjà utilisé",
	loginDoesNotExist: "Ce login n'existe pas",
	invalidPassword: "Mot de passe invalide",
	incorrectPassword: "Mot de passe incorrect",
	passwordDoesNotMatch: "Les mots de passes saisis ne sont pas identiques",
	invalidUsername: "Username invalide"
};

const en = {
	headerText: "Pylos - The Game",
	footerText: "SlipSoft - 2018",
	refresh: "Refresh",
	refreshing: "Refreshing",
	disconnect: "Log out",
	login: "Log in",
	register: "Register",
	loginText: "Have an account ? Click here",
	registerText: "No account yet ? click here",
	loginFieldText: "Connection ID",
	passwordFieldText: "Password",
	passwordConfirmationFieldText: "Type your password again",
	usernameFieldText: "Username",
	unknownError: "Unknown error, please try again later",
	internalServerError: "Internal error, please try again later",
	404: "Erreur 404: Unavailable ressource",
	missingAuth: "Missing Auth",
	invalidAuth: "Invalid Auth",
	unavailableData: "Unavailable Data",
	invalidLogin: "Invalid Login",
	loginInUse: "Login already used",
	loginDoesNotExist: "Login does not exit",
	invalidPassword: "Invalid password",
	incorrectPassword: "incorrect password",
	passwordDoesNotMatch: "passwords are not the same",
	invalidUsername: "invalid username"
};

export default {
	fr, en
};
